### ISSUE TITLE
Is the cpan.org RT queue still a place to report bugs?

### ISSUE THREAD

**Issue by ribasushi** [mariuz/perl-dbd-firebird#35]
As noted in https://rt.cpan.org/Public/Bug/Display.html?id=81619 there are two ways to report bugs for DBD::Firebird. As a perl old-fart I of course prefer RT, hence reported a bunch of bugs there. I can move them here if it helps? Cheers.

**Comment by mariuz** [comment]
So we seems that we go back to github issues 

replaced by https://github.com/mariuz/perl-dbd-firebird/issues/49
